/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _IO_FILE ;
enum _2_merged_$op ;
union _2_merged_$node ;
struct timeval ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
enum _2_merged_$op {
    _2_merged__formal$result_STA_0$value_LIT_0 = 15,
    _2_merged__convert_void_star2void_star$left_STA_0$result_STA_0 = 198,
    _2_merged__store_void_star$right_STA_0$left_STA_1 = 130,
    _2_merged__Eq_int_int2int$left_STA_0$result_STA_0$right_STA_1 = 66,
    _2_merged__branchIfTrue$expr_STA_0$label_LAB_0 = 247,
    _2_merged__goto$label_LAB_0 = 128,
    _2_merged__Mult_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 113,
    _2_merged__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 65,
    _2_merged__load_void_star$left_STA_0$result_STA_0 = 55,
    _2_merged__returnVoid$ = 245,
    _2_merged__call$func_LIT_0 = 211,
    _2_merged__store_int$right_STA_0$left_STA_1 = 149,
    _2_merged__load_int$left_STA_0$result_STA_0 = 74,
    _2_merged__local$result_STA_0$value_LIT_0 = 11,
    _2_merged__constant_int$result_STA_0$value_LIT_0 = 244
} ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int getpagesize() ;
unsigned char _2_merged_$array[1][151]  = { {        _2_merged__constant_int$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _2_merged__formal$result_STA_0$value_LIT_0,        (unsigned char)3,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _2_merged__load_int$left_STA_0$result_STA_0,        _2_merged__Eq_int_int2int$left_STA_0$result_STA_0$right_STA_1, 
            _2_merged__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _2_merged__goto$label_LAB_0,        (unsigned char)34,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _2_merged__formal$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _2_merged__load_void_star$left_STA_0$result_STA_0, 
            _2_merged__convert_void_star2void_star$left_STA_0$result_STA_0,        _2_merged__formal$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _2_merged__load_int$left_STA_0$result_STA_0,        _2_merged__constant_int$result_STA_0$value_LIT_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _2_merged__Mult_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _2_merged__store_int$right_STA_0$left_STA_1,        _2_merged__goto$label_LAB_0,        (unsigned char)4, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _2_merged__goto$label_LAB_0, 
            (unsigned char)102,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _2_merged__constant_int$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _2_merged__formal$result_STA_0$value_LIT_0,        (unsigned char)3,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _2_merged__load_int$left_STA_0$result_STA_0,        _2_merged__Eq_int_int2int$left_STA_0$result_STA_0$right_STA_1, 
            _2_merged__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _2_merged__goto$label_LAB_0,        (unsigned char)75,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _2_merged__local$result_STA_0$value_LIT_0,        (unsigned char)24, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _2_merged__formal$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _2_merged__store_void_star$right_STA_0$left_STA_1,        _2_merged__local$result_STA_0$value_LIT_0,        (unsigned char)32,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _2_merged__formal$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _2_merged__load_int$left_STA_0$result_STA_0, 
            _2_merged__store_int$right_STA_0$left_STA_1,        _2_merged__local$result_STA_0$value_LIT_0,        (unsigned char)36,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _2_merged__formal$result_STA_0$value_LIT_0,        (unsigned char)2, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _2_merged__load_int$left_STA_0$result_STA_0, 
            _2_merged__store_int$right_STA_0$left_STA_1,        _2_merged__call$func_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _2_merged__formal$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _2_merged__load_void_star$left_STA_0$result_STA_0, 
            _2_merged__convert_void_star2void_star$left_STA_0$result_STA_0,        _2_merged__formal$result_STA_0$value_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _2_merged__load_int$left_STA_0$result_STA_0,        _2_merged__formal$result_STA_0$value_LIT_0, 
            (unsigned char)2,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _2_merged__load_int$left_STA_0$result_STA_0,        _2_merged__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _2_merged__store_int$right_STA_0$left_STA_1,        _2_merged__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _2_merged__goto$label_LAB_0,        (unsigned char)9,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _2_merged__goto$label_LAB_0,        (unsigned char)4,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _2_merged__returnVoid$}};
extern int pthread_join(void *thread , void **value_ptr ) ;
extern unsigned int strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern int pthread_barrier_destroy(int *barrier ) ;
void merged(void *tigressRetVal , int x__0 , int y__1 , int whichBlock__2 ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern void abort() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
union _2_merged_$node {
   char _char ;
   unsigned int _unsigned_int ;
   unsigned char _unsigned_char ;
   long _long ;
   unsigned long _unsigned_long ;
   void *_void_star ;
   unsigned short _unsigned_short ;
   unsigned long long _unsigned_long_long ;
   signed char _signed_char ;
   long long _long_long ;
   int _int ;
   short _short ;
};
extern void free(void *ptr ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void exit(int status ) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
extern void signal(int sig , void *func ) ;
void init_tigress(void) ;
typedef struct _IO_FILE FILE;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double ceil(double x ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int fclose(void *stream ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
char const   *_2_merged_$strings  =    "";
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long clock(void) ;
extern long time(long *tloc ) ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern int rand() ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern int strcmp(char const   *a , char const   *b ) ;
extern double sqrt(double x ) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern void *malloc(unsigned int size ) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int atoi(char const   *s ) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
void megaInit(void) ;
void init_tigress(void) 
{ 


  {
  return;
}
}
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) 
{ 
  int x ;
  int y ;
  int z ;
  int tmp ;
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = _formal_argc;
  _global_argv = _formal_argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  x = 6;
  y = 9;
  merged(& tmp, x, y, 1);
  z = tmp;
  printf((char const   */* __restrict  */)"The sum is %d.\n", z);
  return (0);
}
}
void megaInit(void) 
{ 


  {

}
}
void merged(void *tigressRetVal , int x__0 , int y__1 , int whichBlock__2 ) 
{ 
  char _2_merged_$locals[40] ;
  union _2_merged_$node _2_merged_$stack[1][32] ;
  union _2_merged_$node *_2_merged_$sp[1] ;
  unsigned char *_2_merged_$pc[1] ;

  {
  _2_merged_$sp[0] = _2_merged_$stack[0];
  _2_merged_$pc[0] = _2_merged_$array[0];
  while (1) {
    switch (*(_2_merged_$pc[0])) {
    case _2_merged__Eq_int_int2int$left_STA_0$result_STA_0$right_STA_1: 
    (_2_merged_$pc[0]) ++;
    (_2_merged_$sp[0] + -1)->_int = (_2_merged_$sp[0] + 0)->_int == (_2_merged_$sp[0] + -1)->_int;
    (_2_merged_$sp[0]) --;
    break;
    case _2_merged__Mult_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_2_merged_$pc[0]) ++;
    (_2_merged_$sp[0] + -1)->_int = (_2_merged_$sp[0] + -1)->_int * (_2_merged_$sp[0] + 0)->_int;
    (_2_merged_$sp[0]) --;
    break;
    case _2_merged__goto$label_LAB_0: 
    (_2_merged_$pc[0]) ++;
    _2_merged_$pc[0] += *((int *)_2_merged_$pc[0]);
    break;
    case _2_merged__constant_int$result_STA_0$value_LIT_0: 
    (_2_merged_$pc[0]) ++;
    (_2_merged_$sp[0] + 1)->_int = *((int *)_2_merged_$pc[0]);
    (_2_merged_$sp[0]) ++;
    _2_merged_$pc[0] += 4;
    break;
    case _2_merged__call$func_LIT_0: 
    (_2_merged_$pc[0]) ++;
    switch (*((int *)_2_merged_$pc[0])) {
    case 1: 
    merged(*((int **)(_2_merged_$locals + 24)), *((int *)(_2_merged_$locals + 32)),
           *((int *)(_2_merged_$locals + 36)), 0);
    break;
    }
    _2_merged_$pc[0] += 4;
    break;
    case _2_merged__load_void_star$left_STA_0$result_STA_0: 
    (_2_merged_$pc[0]) ++;
    (_2_merged_$sp[0] + 0)->_void_star = *((void **)(_2_merged_$sp[0] + 0)->_void_star);
    break;
    case _2_merged__load_int$left_STA_0$result_STA_0: 
    (_2_merged_$pc[0]) ++;
    (_2_merged_$sp[0] + 0)->_int = *((int *)(_2_merged_$sp[0] + 0)->_void_star);
    break;
    case _2_merged__returnVoid$: 
    (_2_merged_$pc[0]) ++;
    return;
    break;
    case _2_merged__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_2_merged_$pc[0]) ++;
    if ((_2_merged_$sp[0] + 0)->_int) {
      _2_merged_$pc[0] += *((int *)_2_merged_$pc[0]);
    } else {
      _2_merged_$pc[0] += 4;
    }
    (_2_merged_$sp[0]) --;
    break;
    case _2_merged__formal$result_STA_0$value_LIT_0: 
    (_2_merged_$pc[0]) ++;
    switch (*((int *)_2_merged_$pc[0])) {
    case 2: 
    (_2_merged_$sp[0] + 1)->_void_star = (void *)(& y__1);
    break;
    case 1: 
    (_2_merged_$sp[0] + 1)->_void_star = (void *)(& x__0);
    break;
    case 0: 
    (_2_merged_$sp[0] + 1)->_void_star = (void *)(& tigressRetVal);
    break;
    case 3: 
    (_2_merged_$sp[0] + 1)->_void_star = (void *)(& whichBlock__2);
    break;
    }
    (_2_merged_$sp[0]) ++;
    _2_merged_$pc[0] += 4;
    break;
    case _2_merged__convert_void_star2void_star$left_STA_0$result_STA_0: 
    (_2_merged_$pc[0]) ++;
    (_2_merged_$sp[0] + 0)->_void_star = (_2_merged_$sp[0] + 0)->_void_star;
    break;
    case _2_merged__store_int$right_STA_0$left_STA_1: 
    (_2_merged_$pc[0]) ++;
    *((int *)(_2_merged_$sp[0] + -1)->_void_star) = (_2_merged_$sp[0] + 0)->_int;
    _2_merged_$sp[0] += -2;
    break;
    case _2_merged__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_2_merged_$pc[0]) ++;
    (_2_merged_$sp[0] + -1)->_int = (_2_merged_$sp[0] + -1)->_int + (_2_merged_$sp[0] + 0)->_int;
    (_2_merged_$sp[0]) --;
    break;
    case _2_merged__local$result_STA_0$value_LIT_0: 
    (_2_merged_$pc[0]) ++;
    (_2_merged_$sp[0] + 1)->_void_star = (void *)(_2_merged_$locals + *((int *)_2_merged_$pc[0]));
    (_2_merged_$sp[0]) ++;
    _2_merged_$pc[0] += 4;
    break;
    case _2_merged__store_void_star$right_STA_0$left_STA_1: 
    (_2_merged_$pc[0]) ++;
    *((void **)(_2_merged_$sp[0] + -1)->_void_star) = (_2_merged_$sp[0] + 0)->_void_star;
    _2_merged_$sp[0] += -2;
    break;
    }
  }
}
}
