/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _2_init_tigress_1_opaque_NodeStruct ;
union _3_sum_$node ;
struct _IO_FILE ;
struct timeval ;
enum _3_sum_$op ;
struct _2_init_tigress_1_opaque_NodeStruct {
   struct _2_init_tigress_1_opaque_NodeStruct *next ;
   int data ;
   struct _2_init_tigress_1_opaque_NodeStruct *prev ;
};
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int getpagesize() ;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern unsigned int strlen(char const   *s ) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
unsigned long _1_entropy  =    1205847982700084983UL;
extern int ( /* missing proto */  printf)() ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_ptr_2  =    (struct _2_init_tigress_1_opaque_NodeStruct *)0;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
unsigned long _1_alwaysZero  =    0;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern void abort() ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void free(void *ptr ) ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void exit(int status ) ;
extern void signal(int sig , void *func ) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
void init_tigress(void) ;
typedef struct _IO_FILE FILE;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double log(double x ) ;
extern double ceil(double x ) ;
struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_ptr_1  =    (struct _2_init_tigress_1_opaque_NodeStruct *)0;
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
enum _3_sum_$op {
    _3_sum__load_int$left_STA_0$result_STA_0 = 221,
    _3_sum__formal$result_STA_0$value_LIT_0 = 238,
    _3_sum__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 9,
    _3_sum__store_int$right_STA_0$left_STA_1 = 196,
    _3_sum__return_int$expr_STA_0 = 169,
    _3_sum__local$result_STA_0$value_LIT_0 = 3,
    _3_sum__goto$label_LAB_0 = 82
} ;
extern void perror(char const   *str ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
char const   *_3_sum_$strings  =    "";
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
typedef struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_StructureType;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_list_1  =    (struct _2_init_tigress_1_opaque_NodeStruct *)0;
extern float strtof(char const   *str , char const   *endptr ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
unsigned char _3_sum_$array[1][31]  = { {        _3_sum__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_sum__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _3_sum__load_int$left_STA_0$result_STA_0,        _3_sum__formal$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _3_sum__load_int$left_STA_0$result_STA_0,        _3_sum__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _3_sum__store_int$right_STA_0$left_STA_1,        _3_sum__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _3_sum__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _3_sum__load_int$left_STA_0$result_STA_0,        _3_sum__return_int$expr_STA_0}};
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
extern int rand() ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
union _3_sum_$node {
   char _char ;
   unsigned int _unsigned_int ;
   unsigned char _unsigned_char ;
   long _long ;
   unsigned long _unsigned_long ;
   void *_void_star ;
   unsigned short _unsigned_short ;
   unsigned long long _unsigned_long_long ;
   signed char _signed_char ;
   long long _long_long ;
   int _int ;
   short _short ;
};
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern void *malloc(unsigned int size ) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int atoi(char const   *s ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
unsigned int _2_init_tigress__opaque_array[30]  = 
  {      258,      691,      3,      308, 
        425,      5,      278,      537, 
        5,      3,      187,      7, 
        33,      12,      57,      358, 
        670,      43,      448,      159, 
        85,      468,      292,      13, 
        143,      243,      80,      498, 
        369};
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_list_2  =    (struct _2_init_tigress_1_opaque_NodeStruct *)0;
int sum(int x , int y ) ;
void megaInit(void) ;
void init_tigress(void) 
{ 
  struct _2_init_tigress_1_opaque_NodeStruct *p1 ;
  int i2 ;
  struct _2_init_tigress_1_opaque_NodeStruct *p3 ;
  int _2_init_tigress__BEGIN_1 ;
  int _2_init_tigress__END_1 ;
  int _2_init_tigress__BARRIER_2 ;

  {
  _2_init_tigress__BEGIN_1 = 1;
  p1 = (struct _2_init_tigress_1_opaque_NodeStruct *)malloc(sizeof(struct _2_init_tigress_1_opaque_NodeStruct ));
  p1->next = p1;
  p1->prev = p1;
  _2_init_tigress_1_opaque_list_1 = p1;
  i2 = 0;
  while (i2 < 4) {
    p3 = (struct _2_init_tigress_1_opaque_NodeStruct *)malloc(sizeof(struct _2_init_tigress_1_opaque_NodeStruct ));
    p3->data = i2 * (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL)));
    p3->next = _2_init_tigress_1_opaque_list_1->next;
    p3->prev = _2_init_tigress_1_opaque_list_1;
    (_2_init_tigress_1_opaque_list_1->next)->prev = p3;
    _2_init_tigress_1_opaque_list_1->next = p3;
    i2 ++;
  }
  _2_init_tigress_1_opaque_ptr_1 = _2_init_tigress_1_opaque_list_1->next;
  _2_init_tigress_1_opaque_ptr_2 = _2_init_tigress_1_opaque_ptr_1;
  _2_init_tigress_1_opaque_ptr_2 = _2_init_tigress_1_opaque_ptr_2->next;
  _2_init_tigress__END_1 = 1;
  _2_init_tigress__BARRIER_2 = 1;
  return;
}
}
int sum(int x , int y ) 
{ 
  char _3_sum_$locals[12] ;
  union _3_sum_$node _3_sum_$stack[1][32] ;
  union _3_sum_$node *_3_sum_$sp[1] ;
  unsigned char *_3_sum_$pc[1] ;
  unsigned char _3_sum_$currentOp ;
  unsigned char left11 ;
  unsigned char right12 ;
  unsigned char result13 ;
  unsigned char left14 ;
  unsigned char right15 ;
  unsigned char result16 ;
  unsigned char left17 ;
  unsigned char right18 ;
  unsigned char result19 ;
  unsigned char left20 ;
  unsigned char right21 ;
  unsigned char result22 ;
  unsigned char left23 ;
  unsigned char right24 ;
  unsigned char result25 ;
  unsigned char left26 ;
  unsigned char right27 ;
  unsigned char result28 ;
  int left29 ;
  int right30 ;
  int result31 ;
  int selfModify_BEGIN_3 ;
  int selfModify_END_3 ;
  unsigned long *addrPtr34 ;
  unsigned int *opPtr35 ;
  int selfModify_BEGIN_4 ;
  int selfModify_END_4 ;
  unsigned char left38 ;
  unsigned char right39 ;
  unsigned char result40 ;

  {
  if (_2_init_tigress__opaque_array[((unsigned int )(((_1_entropy | 9) + ((long )(_1_entropy | 9) >> 63L)) ^ ((long )(_1_entropy | 9) >> 63L)) % 10) * 3 + 0] % _2_init_tigress__opaque_array[5] != _2_init_tigress__opaque_array[2]) {
    goto *((void *)((_1_entropy & 3) * (_1_entropy | 3) + (_1_entropy & ~ 3) * (~ _1_entropy & 3)));
  } else {

  }
  addrPtr34 = (unsigned long *)((unsigned long )(&& Lab_2000001) + 34);
  *addrPtr34 = (unsigned long )(& left29);
  addrPtr34 = (unsigned long *)((unsigned long )(&& Lab_2000001) + 66);
  *addrPtr34 = (unsigned long )(& right30);
  addrPtr34 = (unsigned long *)((unsigned long )(&& Lab_2000001) + 112);
  *addrPtr34 = (unsigned long )(& result31);
  opPtr35 = (unsigned int *)((unsigned long )(&& Lab_2000001) + 96);
  addrPtr34 = (unsigned long *)((unsigned long )(&& Lab_2000001) + 170);
  *addrPtr34 = (unsigned long )(&& Lab_2000002);
  selfModify_BEGIN_3 = 1;
  Lab_2000001: /* CIL Label */ 
  __asm__  volatile   (".byte 0x9b,0xf9,0xf9,0xf5,0x90,0xf9,0x9b,0xf5,0xf5,0xfc;\n"
                       ".byte 0x50;\n"
                       ".byte 0xf5,0x90,0xfd,0xfd,0x9b,0x90,0xf8,0x90,0x90,0xfd;\n"
                       ".byte 0x51;\n"
                       ".byte 0xf5,0xf8,0x9b,0xf8,0xf9,0xf5,0x9b,0xfc,0x9b,0xfc;\n"
                       ".byte 0x48, 0xb8, 0xba,0xfe,0xbf,0xc,0x98,0x82,0xce,0xba;\n"
                       ".byte 0xf9,0x90,0x90,0x9b,0x9b,0xf9,0x9b,0xf9,0xf5,0x90;\n"
                       ".byte 0x8b, 0x00;\n"
                       ".byte 0xf8,0xf9,0xfd,0xfd,0xf9,0x90,0xf8,0x90,0xf5,0xf9;\n"
                       ".byte 0x48, 0xb9,  0xaa,0xa0,0x4c,0x99,0xf3,0x41,0x8a,0x1f;\n"
                       ".byte 0x9b,0x90,0xfc,0xf9,0xf9,0xf8,0xf9,0x9b,0xfc,0x9b;\n"
                       ".byte 0x8b, 0x09;\n"
                       ".byte 0x9b,0xfd,0x90,0x9b,0xfc,0xfd,0x9b,0xf5,0xf5,0xfd;\n"
                       ".byte  0x90, 0x01, 0xc8, 0x90;\n"
                       ".byte 0xf9,0x9b,0x90,0xf9,0xfc,0x9b,0x90,0x90,0xf9,0xf5;\n"
                       ".byte 0x48, 0xb9, 0xe4,0xe8,0xd7,0xc6,0x78,0x78,0x14,0xcd;\n"
                       ".byte 0xfc,0xf9,0xfd,0xf5,0xf9,0xf5,0xf8,0xf5,0xf9,0xfc;\n"
                       ".byte 0x89, 0x01;\n"
                       ".byte 0x90,0x9b,0xfc,0xf5,0xfd,0xf9,0xf9,0xf8,0x90,0xfc;\n"
                       ".byte 0x59;\n"
                       ".byte 0xfc,0xfc,0xf8,0xf8,0xfc,0x90,0xfc,0xfd,0xf8,0xfd;\n"
                       ".byte 0x58;\n"
                       ".byte 0xf8,0x9b,0xfd,0xfd,0xfd,0x9b,0x9b,0xf5,0xfc,0x9b;\n"
                       ".byte 0xff, 0x25, 00, 00, 00, 00, 0xfc,0x21,0x9e,0x25,0x66,0xe9,0xfc,0x6a;\n"
                       ".byte 0x90,0xf9,0xfd,0xf8,0x9b,0x9b,0xfc,0x90,0xf5,0xfc;\n":);
  Lab_2000002: /* CIL Label */ 
  selfModify_END_3 = 1;
  {
  _3_sum_$sp[0] = _3_sum_$stack[0];
  _3_sum_$pc[0] = _3_sum_$array[0];
  }
  while (1) {
    {
    _3_sum_$currentOp = *(_3_sum_$pc[0]);
    }
    if (_3_sum_$currentOp == _3_sum__store_int$right_STA_0$left_STA_1) {
      {
      (_3_sum_$pc[0]) ++;
      *((int *)(_3_sum_$sp[0] + -1)->_void_star) = (_3_sum_$sp[0] + 0)->_int;
      _3_sum_$sp[0] += -2;
      }
    } else
    if (_3_sum_$currentOp == _3_sum__load_int$left_STA_0$result_STA_0) {
      {
      (_3_sum_$pc[0]) ++;
      (_3_sum_$sp[0] + 0)->_int = *((int *)(_3_sum_$sp[0] + 0)->_void_star);
      }
    } else
    if (_3_sum_$currentOp == _3_sum__formal$result_STA_0$value_LIT_0) {
      {
      (_3_sum_$pc[0]) ++;
      }
      switch (*((int *)_3_sum_$pc[0])) {
      case 1: 
      {
      (_3_sum_$sp[0] + 1)->_void_star = (void *)(& y);
      }
      break;
      case 0: 
      {
      (_3_sum_$sp[0] + 1)->_void_star = (void *)(& x);
      }
      break;
      }
      {
      (_3_sum_$sp[0]) ++;
      _3_sum_$pc[0] += 4;
      }
    } else
    if (_3_sum_$currentOp == _3_sum__goto$label_LAB_0) {
      {
      (_3_sum_$pc[0]) ++;
      _3_sum_$pc[0] += *((int *)_3_sum_$pc[0]);
      }
    } else
    if (_3_sum_$currentOp == _3_sum__return_int$expr_STA_0) {
      {
      (_3_sum_$pc[0]) ++;
      }
      return ((_3_sum_$sp[0] + 0)->_int);
    } else
    if (_3_sum_$currentOp == _3_sum__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1) {
      {
      (_3_sum_$pc[0]) ++;
      {
      left29 = (_3_sum_$sp[0] + -1)->_int;
      right30 = (_3_sum_$sp[0] + 0)->_int;
      addrPtr34 = (unsigned long *)((unsigned long )(&& Lab_2000003) + 6);
      *addrPtr34 = (unsigned long )(&& Lab_2000001);
      addrPtr34 = (unsigned long *)((unsigned long )(&& Lab_2000001) + 170);
      *addrPtr34 = (unsigned long )(&& Lab_2000004);
      *opPtr35 = 2429026704U;
      selfModify_BEGIN_4 = 1;
      Lab_2000003: /* CIL Label */ 
      __asm__  volatile   (".byte 0xff, 0x25, 00, 00, 00, 00, 0xf0,0x15,0xa3,0xca,0x6a,0x65,0xef,0x31;\n":);
      Lab_2000004: /* CIL Label */ 
      selfModify_END_4 = 1;
      (_3_sum_$sp[0] + -1)->_int = result31;
      }
      (_3_sum_$sp[0]) --;
      }
    } else
    if (_3_sum_$currentOp == _3_sum__local$result_STA_0$value_LIT_0) {
      {
      (_3_sum_$pc[0]) ++;
      (_3_sum_$sp[0] + 1)->_void_star = (void *)(_3_sum_$locals + *((int *)_3_sum_$pc[0]));
      (_3_sum_$sp[0]) ++;
      _3_sum_$pc[0] += 4;
      }
    } else {
      {

      }
    }
  }
}
}
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) 
{ 
  int x ;
  int y ;
  int z ;
  int tmp ;
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = _formal_argc;
  _global_argv = _formal_argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  x = 6;
  y = 9;
  tmp = sum(x, y);
  z = tmp;
  printf("The sum is %d.\n", z);
  return (0);
}
}
void megaInit(void) 
{ 


  {

}
}
