/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

union _1_sum_$node ;
struct _IO_FILE ;
struct timeval ;
enum _1_sum_$op ;
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
enum _1_sum_$op {
    _1_sum__store_int$right_STA_0$left_STA_1 = 55,
    _1_sum__store_void_star$right_STA_0$left_STA_1 = 211,
    _1_sum__return_int$expr_STA_0 = 245,
    _1_sum__formal$result_STA_0$value_LIT_0 = 65,
    _1_sum__branchIfTrue$expr_STA_0$label_LAB_0 = 66,
    _1_sum__convert_unsigned_long2void_star$left_STA_0$result_STA_0 = 113,
    _1_sum__Eq_void_star_void_star2int$right_STA_0$result_STA_0$left_STA_1 = 244,
    _1_sum__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1 = 15,
    _1_sum__call$func_LIT_0 = 74,
    _1_sum__constant_unsigned_long$result_STA_0$value_LIT_0 = 109,
    _1_sum__global$result_STA_0$value_LIT_0 = 247,
    _1_sum__load_int$left_STA_0$result_STA_0 = 136,
    _1_sum__goto$label_LAB_0 = 198,
    _1_sum__local$result_STA_0$value_LIT_0 = 128,
    _1_sum__load_void_star$left_STA_0$result_STA_0 = 130,
    _1_sum__string$result_STA_0$value_LIT_0 = 11
} ;
unsigned char _1_sum_$array[2][121]  = { {        _1_sum__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_sum__formal$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_sum__load_int$left_STA_0$result_STA_0,        _1_sum__formal$result_STA_0$value_LIT_0, 
            (unsigned char)1,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_sum__load_int$left_STA_0$result_STA_0,        _1_sum__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,        _1_sum__store_int$right_STA_0$left_STA_1,        _1_sum__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_sum__local$result_STA_0$value_LIT_0,        (unsigned char)8,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_sum__load_int$left_STA_0$result_STA_0,        _1_sum__return_int$expr_STA_0}, {        _1_sum__global$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_sum__load_void_star$left_STA_0$result_STA_0,        _1_sum__constant_unsigned_long$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_sum__convert_unsigned_long2void_star$left_STA_0$result_STA_0, 
            _1_sum__Eq_void_star_void_star2int$right_STA_0$result_STA_0$left_STA_1,        _1_sum__branchIfTrue$expr_STA_0$label_LAB_0,        (unsigned char)9,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_sum__goto$label_LAB_0,        (unsigned char)48, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_sum__local$result_STA_0$value_LIT_0, 
            (unsigned char)16,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_sum__string$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_sum__store_void_star$right_STA_0$left_STA_1,        _1_sum__local$result_STA_0$value_LIT_0,        (unsigned char)24, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_sum__string$result_STA_0$value_LIT_0, 
            (unsigned char)10,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_sum__store_void_star$right_STA_0$left_STA_1,        _1_sum__call$func_LIT_0,        (unsigned char)1,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_sum__global$result_STA_0$value_LIT_0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_sum__local$result_STA_0$value_LIT_0, 
            (unsigned char)32,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_sum__load_void_star$left_STA_0$result_STA_0,        _1_sum__store_void_star$right_STA_0$left_STA_1,        _1_sum__goto$label_LAB_0,        (unsigned char)9, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_sum__goto$label_LAB_0, 
            (unsigned char)4,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_sum__local$result_STA_0$value_LIT_0,        (unsigned char)40,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_sum__global$result_STA_0$value_LIT_0,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_sum__load_void_star$left_STA_0$result_STA_0,        _1_sum__store_void_star$right_STA_0$left_STA_1, 
            _1_sum__local$result_STA_0$value_LIT_0,        (unsigned char)48,        (unsigned char)0,        (unsigned char)0, 
            (unsigned char)0,        _1_sum__string$result_STA_0$value_LIT_0,        (unsigned char)12,        (unsigned char)0, 
            (unsigned char)0,        (unsigned char)0,        _1_sum__store_void_star$right_STA_0$left_STA_1,        _1_sum__call$func_LIT_0, 
            (unsigned char)2,        (unsigned char)0,        (unsigned char)0,        (unsigned char)0, 
            _1_sum__goto$label_LAB_0,        (unsigned char)151,        (unsigned char)255,        (unsigned char)255, 
            (unsigned char)255,        _1_sum__goto$label_LAB_0,        (unsigned char)146,        (unsigned char)255, 
            (unsigned char)255,        (unsigned char)255,        _1_sum__formal$result_STA_0$value_LIT_0,        (unsigned char)1, 
            (unsigned char)0,        (unsigned char)0,        (unsigned char)0,        _1_sum__load_int$left_STA_0$result_STA_0, 
            _1_sum__return_int$expr_STA_0}};
char **_global_argv  =    (char **)0;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
void *_1_sum_$devNull  =    0;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern unsigned int strlen(char const   *s ) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int printf(char const   * __restrict  __format  , ...) ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
char const   *_1_sum_$strings  =    "/dev/null\000a\000collatz n=%i\n\000";
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void abort() ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
extern void signal(int sig , void *func ) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
extern void exit(int status ) ;
void init_tigress(void) ;
typedef struct _IO_FILE FILE;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double log(double x ) ;
extern double ceil(double x ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int fclose(void *stream ) ;
union _1_sum_$node {
   char _char ;
   unsigned int _unsigned_int ;
   unsigned char _unsigned_char ;
   long _long ;
   unsigned long _unsigned_long ;
   void *_void_star ;
   unsigned short _unsigned_short ;
   unsigned long long _unsigned_long_long ;
   signed char _signed_char ;
   long long _long_long ;
   int _int ;
   short _short ;
};
extern void perror(char const   *str ) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern int rand() ;
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern void *malloc(unsigned int size ) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
extern int atoi(char const   *s ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
int sum(int x , int y ) ;
void megaInit(void) ;
void megaInit(void) 
{ 


  {

}
}
void init_tigress(void) 
{ 


  {
  return;
}
}
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) 
{ 
  int x ;
  int y ;
  int z ;
  int tmp ;
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = _formal_argc;
  _global_argv = _formal_argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  x = 6;
  y = 9;
  tmp = sum(x, y);
  z = tmp;
  printf((char const   */* __restrict  */)"The sum is %d.\n", z);
  return (0);
}
}
int sum(int x , int y ) 
{ 
  char _1_sum_$locals[56] ;
  register int _1_sum_$select ;
  union _1_sum_$node _1_sum_$stack[2][32] ;
  union _1_sum_$node *_1_sum_$sp[2] ;
  unsigned char *_1_sum_$pc[2] ;

  {
  _1_sum_$select = 0 >= 2 ? 0 - 2 : 0;
  _1_sum_$sp[_1_sum_$select] = _1_sum_$stack[_1_sum_$select];
  _1_sum_$select = 1 % 2;
  _1_sum_$sp[_1_sum_$select] = _1_sum_$stack[_1_sum_$select];
  _1_sum_$select = 0 >= 2 ? 0 - 2 : 0;
  _1_sum_$pc[_1_sum_$select] = _1_sum_$array[_1_sum_$select];
  _1_sum_$select = 1 >= 2 ? 1 - 2 : 1;
  _1_sum_$pc[_1_sum_$select] = _1_sum_$array[_1_sum_$select];
  _1_sum_$select = 0 >= 2 ? 0 - 2 : 0;
  while (1) {
    switch (*(_1_sum_$pc[_1_sum_$select])) {
    case _1_sum__constant_unsigned_long$result_STA_0$value_LIT_0: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    (_1_sum_$sp[_1_sum_$select] + 1)->_unsigned_long = *((unsigned long *)_1_sum_$pc[_1_sum_$select]);
    (_1_sum_$sp[_1_sum_$select]) ++;
    _1_sum_$pc[_1_sum_$select] += 8;
    break;
    case _1_sum__call$func_LIT_0: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    switch (*((int *)_1_sum_$pc[_1_sum_$select])) {
    case 1: 
    *((void **)(_1_sum_$locals + 32)) = fopen(*((char const   **)(_1_sum_$locals + 16)),
                                              *((char const   **)(_1_sum_$locals + 24)));
    break;
    case 2: 
    fprintf(*((void **)(_1_sum_$locals + 40)), *((char const   **)(_1_sum_$locals + 48)),
            1);
    break;
    }
    _1_sum_$pc[_1_sum_$select] += 4;
    break;
    case _1_sum__string$result_STA_0$value_LIT_0: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    (_1_sum_$sp[_1_sum_$select] + 1)->_void_star = (void *)(_1_sum_$strings + *((int *)_1_sum_$pc[_1_sum_$select]));
    (_1_sum_$sp[_1_sum_$select]) ++;
    _1_sum_$pc[_1_sum_$select] += 4;
    break;
    case _1_sum__store_int$right_STA_0$left_STA_1: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    *((int *)(_1_sum_$sp[_1_sum_$select] + -1)->_void_star) = (_1_sum_$sp[_1_sum_$select] + 0)->_int;
    _1_sum_$sp[_1_sum_$select] += -2;
    break;
    case _1_sum__load_int$left_STA_0$result_STA_0: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    (_1_sum_$sp[_1_sum_$select] + 0)->_int = *((int *)(_1_sum_$sp[_1_sum_$select] + 0)->_void_star);
    break;
    case _1_sum__formal$result_STA_0$value_LIT_0: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    switch (*((int *)_1_sum_$pc[_1_sum_$select])) {
    case 1: 
    (_1_sum_$sp[_1_sum_$select] + 1)->_void_star = (void *)(& y);
    break;
    case 0: 
    (_1_sum_$sp[_1_sum_$select] + 1)->_void_star = (void *)(& x);
    break;
    }
    (_1_sum_$sp[_1_sum_$select]) ++;
    _1_sum_$pc[_1_sum_$select] += 4;
    break;
    case _1_sum__global$result_STA_0$value_LIT_0: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    switch (*((int *)_1_sum_$pc[_1_sum_$select])) {
    case 0: 
    (_1_sum_$sp[_1_sum_$select] + 1)->_void_star = (void *)(& _1_sum_$devNull);
    break;
    }
    (_1_sum_$sp[_1_sum_$select]) ++;
    _1_sum_$pc[_1_sum_$select] += 4;
    break;
    case _1_sum__convert_unsigned_long2void_star$left_STA_0$result_STA_0: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    (_1_sum_$sp[_1_sum_$select] + 0)->_void_star = (void *)(_1_sum_$sp[_1_sum_$select] + 0)->_unsigned_long;
    break;
    case _1_sum__branchIfTrue$expr_STA_0$label_LAB_0: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    if ((_1_sum_$sp[_1_sum_$select] + 0)->_int) {
      _1_sum_$pc[_1_sum_$select] += *((int *)_1_sum_$pc[_1_sum_$select]);
    } else {
      _1_sum_$pc[_1_sum_$select] += 4;
    }
    (_1_sum_$sp[_1_sum_$select]) --;
    break;
    case _1_sum__goto$label_LAB_0: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    _1_sum_$pc[_1_sum_$select] += *((int *)_1_sum_$pc[_1_sum_$select]);
    break;
    case _1_sum__load_void_star$left_STA_0$result_STA_0: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    (_1_sum_$sp[_1_sum_$select] + 0)->_void_star = *((void **)(_1_sum_$sp[_1_sum_$select] + 0)->_void_star);
    break;
    case _1_sum__Eq_void_star_void_star2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    (_1_sum_$sp[_1_sum_$select] + -1)->_int = (_1_sum_$sp[_1_sum_$select] + -1)->_void_star == (_1_sum_$sp[_1_sum_$select] + 0)->_void_star;
    (_1_sum_$sp[_1_sum_$select]) --;
    break;
    case _1_sum__return_int$expr_STA_0: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    return ((_1_sum_$sp[_1_sum_$select] + 0)->_int);
    break;
    case _1_sum__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    (_1_sum_$sp[_1_sum_$select] + -1)->_int = (_1_sum_$sp[_1_sum_$select] + -1)->_int + (_1_sum_$sp[_1_sum_$select] + 0)->_int;
    (_1_sum_$sp[_1_sum_$select]) --;
    break;
    case _1_sum__store_void_star$right_STA_0$left_STA_1: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    *((void **)(_1_sum_$sp[_1_sum_$select] + -1)->_void_star) = (_1_sum_$sp[_1_sum_$select] + 0)->_void_star;
    _1_sum_$sp[_1_sum_$select] += -2;
    break;
    case _1_sum__local$result_STA_0$value_LIT_0: 
    (_1_sum_$pc[_1_sum_$select]) ++;
    (_1_sum_$sp[_1_sum_$select] + 1)->_void_star = (void *)(_1_sum_$locals + *((int *)_1_sum_$pc[_1_sum_$select]));
    (_1_sum_$sp[_1_sum_$select]) ++;
    _1_sum_$pc[_1_sum_$select] += 4;
    break;
    }
    _1_sum_$select = _1_sum_$select + 1 >= 2 ? (_1_sum_$select + 1) - 2 : _1_sum_$select + 1;
  }
}
}
