/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

#include <stdio.h>
void _cipher$_xtea_encipherBlock(unsigned int num_rounds , unsigned int *v , unsigned int *key ) 
{ 
  unsigned int v0 ;
  unsigned int v1 ;
  unsigned int delta ;
  unsigned int sum ;
  unsigned int i ;

  {
  v0 = v[0];
  v1 = v[1];
  delta = 2117564857;
  sum = 0;
  i = 0;
  while (i < num_rounds) {
    v0 += (((v1 << 4) ^ (v1 >> 5)) + v1) ^ (sum + key[sum & 3]);
    sum += delta;
    v1 += (((v0 << 4) ^ (v0 >> 5)) + v0) ^ (sum + key[(sum >> 11) & 3]);
    i ++;
  }
  v[0] = v0;
  v[1] = v1;
}
}
void _cipher$_xtea_decipherBlock(unsigned int num_rounds , unsigned int *v , unsigned int *key ) 
{ 
  unsigned int v0 ;
  unsigned int v1 ;
  unsigned int delta ;
  unsigned int sum ;
  unsigned int i ;

  {
  v0 = v[0];
  v1 = v[1];
  delta = 2117564857;
  sum = delta * num_rounds;
  i = 0;
  while (i < num_rounds) {
    v1 -= (((v0 << 4) ^ (v0 >> 5)) + v0) ^ (sum + key[(sum >> 11) & 3]);
    sum -= delta;
    v0 -= (((v1 << 4) ^ (v1 >> 5)) + v1) ^ (sum + key[sum & 3]);
    i ++;
  }
  v[0] = v0;
  v[1] = v1;
}
}
void _cipher$_xtea_encipher(unsigned int block_no , unsigned int num_rounds , unsigned int *v ,
                            unsigned int *key , unsigned int size ) 
{ 
  unsigned int i ;

  {
  i = 0;
  while (i < size / 8) {
    _cipher$_xtea_encipherBlock(num_rounds, v, key);
    v += 2;
    i ++;
  }
}
}
void _cipher$_xtea_decipher(unsigned int block_no , unsigned int num_rounds , unsigned int *v ,
                            unsigned int *key , unsigned int size ) 
{ 
  unsigned int i ;

  {
  i = 0;
  while (i < size / 8) {
    _cipher$_xtea_decipherBlock(num_rounds, v, key);
    v += 2;
    i ++;
  }
}
}
void DUMP_byte(int block , unsigned char *from , long length ) 
{ 
  unsigned char *j ;

  {
  printf("BLOCK %i byte ", block);
  printf(" %ld ", length);
  j = from;
  while (j < from + length) {
    printf("%u ", *j);
    j ++;
  }
  printf(" 0\n");
}
}
void DUMP_short(int block , unsigned short *from , long length ) 
{ 
  unsigned short *j ;

  {
  printf("BLOCK %i short ", block);
  printf(" %ld ", length);
  j = from;
  while (j < from + length) {
    printf("%u ", *j);
    j ++;
  }
  printf(" 0\n");
}
}
void DUMP_int(int block , unsigned int *from , long length ) 
{ 
  unsigned int *j ;

  {
  printf("BLOCK %i int ", block);
  printf(" %ld ", length);
  j = from;
  while (j < from + length) {
    printf("%u ", *j);
    j ++;
  }
  printf(" 0\n");
}
}
int main(void) 
{ 
  unsigned int _4_sum__block_31_1[4]  = {3363671368U, 1208453960U, 3875483787U, 2425393296U};
  unsigned int KEY_1918301893_3786249548_975574495_634376995[4]  = {1918301893U, 3786249548U,
                                                                    975574495U, 634376995U};
  unsigned int _4_sum__block_26_3[4]  = {3363671368U, 1208453960U, 3875483787U, 2425393296U};
  unsigned int _4_sum__block_24_4[4]  = {3363671368U, 1208453960U, 3875483787U, 2425393296U};
  unsigned int _4_sum__block_28_5[4]  = {3363671368U, 1208453960U, 3875483787U, 2425393296U};
  unsigned int _4_sum__block_30_6[4]  = {3363671368U, 1208453960U, 3875483787U, 2425393296U};
  unsigned int _4_sum__block_7_7[12]  = {3233647944U, 1224736766U, 3192391563U, 1U,
                                         0U, 1289128776U, 3242838667U, 2370700257U,
                                         2370570260U, 2303579229U, 2425393178U, 2425393296U};
  unsigned int _4_sum__block_5_8[12]  = {3233647944U, 1224736766U, 3192391563U, 1U,
                                         0U, 1289128776U, 3242838667U, 2370700257U,
                                         2370570260U, 2303578205U, 2425393178U, 2425393296U};
  unsigned int _4_sum__block_15_9[38]  = {3363671368U, 3360001352U, 1211140936U, 442U,
                                          0U, 3398126592U, 1238469453U, 1308877505U,
                                          1276517517U, 2370314121U, 4294885565U, 126568703U,
                                          4294950472U, 4294967295U, 2336817151U, 3398126806U,
                                          65126729U, 135564622U, 1209699149U, 4274036109U,
                                          2337079295U, 3375581219U, 1307675468U, 3242851979U,
                                          2370765799U, 1665743876U, 193544456U, 3233647944U,
                                          1224736766U, 4274029965U, 2336817151U, 4273621040U,
                                          4294967295U, 1291845631U, 2337131147U, 3804318161U,
                                          479022595U, 529091606U};
  unsigned int _4_sum__block_13_10[22]  = {3233647944U, 1224736766U, 4274029965U,
                                           2336817151U, 28985392U, 0U, 1275068416U,
                                           2337131147U, 3804318161U, 479022595U, 529091606U,
                                           3363671368U, 3360001352U, 1211140936U,
                                           442U, 0U, 3398126592U, 1238469453U, 1308877505U,
                                           1276517517U, 2425364361U, 2425393296U};
  unsigned int _4_sum__block_19_11[20]  = {3363671368U, 3360001352U, 1211140936U,
                                           442U, 0U, 3398126592U, 1238469453U, 1308877505U,
                                           1276517517U, 2370314121U, 2370357373U,
                                           2336802885U, 1435322416U, 176901320U, 1292985165U,
                                           2336873099U, 3821095131U, 613239811U, 663309342U,
                                           2425393296U};
  unsigned int _4_sum__block_23_12[4]  = {3363671368U, 1208453960U, 3875483787U, 2425393296U};
  unsigned int _4_sum__block_14_13[48]  = {3363671368U, 3360001352U, 1211140936U,
                                           442U, 0U, 3398126592U, 1238469453U, 1308877505U,
                                           1276517517U, 2370314121U, 4294885565U,
                                           126568703U, 4294950472U, 4294967295U, 2336817151U,
                                           3398126806U, 65126729U, 135564622U, 3231550796U,
                                           1241513982U, 3158907787U, 4294967295U,
                                           4294967295U, 1307872077U, 3242851979U,
                                           2370438119U, 1665940236U, 2374846465U,
                                           4294966976U, 1211730764U, 2337065267U,
                                           3465234929U, 65126728U, 255102285U, 1292788553U,
                                           1158165645U, 2370318985U, 4294885565U,
                                           2240628991U, 4294966976U, 1211140936U,
                                           4294967226U, 4294967295U, 3398126847U,
                                           1238469453U, 1308877505U, 1276517517U,
                                           2425364361U};
  unsigned int _4_sum__block_3_14[26]  = {3363671368U, 3360001352U, 1211140936U, 442U,
                                          0U, 3398126592U, 1238469453U, 1308877505U,
                                          1276517517U, 2370314121U, 4294885565U, 126568703U,
                                          1224094536U, 2337068683U, 3787540938U, 344804867U,
                                          2643282952U, 4294966976U, 1293650761U, 2336875571U,
                                          4052438220U, 65454409U, 859606350U, 1225231181U,
                                          2302740579U, 2425393162U};
  unsigned int _4_sum__block_18_15[46]  = {3361049928U, 3360001352U, 1225296712U,
                                           440U, 0U, 3364572416U, 1238469453U, 1308877505U,
                                           1276189837U, 2370312841U, 4294885525U,
                                           42682623U, 112968U, 0U, 2337013760U, 3364572609U,
                                           65126729U, 135564622U, 3697118540U, 3361574216U,
                                           1294175052U, 1294218339U, 2370567819U,
                                           2303277884U, 2509064250U, 4294966976U,
                                           3229977928U, 1224736766U, 3091794059U,
                                           1U, 0U, 1304988493U, 3242840459U, 2370700258U,
                                           2303463708U, 1435322394U, 1166887112U,
                                           143345864U, 112713U, 0U, 2337079296U, 3515567560U,
                                           65192265U, 287083854U, 2417658188U, 2425393296U};
  unsigned int _4_sum__block_16_16[20]  = {3363671368U, 3360001352U, 1211140936U,
                                           442U, 0U, 3398126592U, 1238469453U, 1308877505U,
                                           1276517517U, 2370314121U, 2370361469U,
                                           4294885509U, 814434559U, 1288844104U, 2337131147U,
                                           3804318161U, 479022595U, 459491606U, 2425364361U,
                                           2425393296U};
  unsigned int _4_sum__block_22_17[4]  = {3363671368U, 1208453960U, 3875483787U, 2425393296U};

  {
  _cipher$_xtea_encipher(22U, 32U, (unsigned int *)_4_sum__block_22_17, KEY_1918301893_3786249548_975574495_634376995,
                         16U);
  DUMP_int(22, _4_sum__block_22_17, 4);
  _cipher$_xtea_encipher(16U, 32U, (unsigned int *)_4_sum__block_16_16, KEY_1918301893_3786249548_975574495_634376995,
                         80U);
  DUMP_int(16, _4_sum__block_16_16, 20);
  _cipher$_xtea_encipher(18U, 32U, (unsigned int *)_4_sum__block_18_15, KEY_1918301893_3786249548_975574495_634376995,
                         184U);
  DUMP_int(18, _4_sum__block_18_15, 46);
  _cipher$_xtea_encipher(3U, 32U, (unsigned int *)_4_sum__block_3_14, KEY_1918301893_3786249548_975574495_634376995,
                         104U);
  DUMP_int(3, _4_sum__block_3_14, 26);
  _cipher$_xtea_encipher(14U, 32U, (unsigned int *)_4_sum__block_14_13, KEY_1918301893_3786249548_975574495_634376995,
                         192U);
  DUMP_int(14, _4_sum__block_14_13, 48);
  _cipher$_xtea_encipher(23U, 32U, (unsigned int *)_4_sum__block_23_12, KEY_1918301893_3786249548_975574495_634376995,
                         16U);
  DUMP_int(23, _4_sum__block_23_12, 4);
  _cipher$_xtea_encipher(19U, 32U, (unsigned int *)_4_sum__block_19_11, KEY_1918301893_3786249548_975574495_634376995,
                         80U);
  DUMP_int(19, _4_sum__block_19_11, 20);
  _cipher$_xtea_encipher(13U, 32U, (unsigned int *)_4_sum__block_13_10, KEY_1918301893_3786249548_975574495_634376995,
                         88U);
  DUMP_int(13, _4_sum__block_13_10, 22);
  _cipher$_xtea_encipher(15U, 32U, (unsigned int *)_4_sum__block_15_9, KEY_1918301893_3786249548_975574495_634376995,
                         152U);
  DUMP_int(15, _4_sum__block_15_9, 38);
  _cipher$_xtea_encipher(5U, 32U, (unsigned int *)_4_sum__block_5_8, KEY_1918301893_3786249548_975574495_634376995,
                         48U);
  DUMP_int(5, _4_sum__block_5_8, 12);
  _cipher$_xtea_encipher(7U, 32U, (unsigned int *)_4_sum__block_7_7, KEY_1918301893_3786249548_975574495_634376995,
                         48U);
  DUMP_int(7, _4_sum__block_7_7, 12);
  _cipher$_xtea_encipher(30U, 32U, (unsigned int *)_4_sum__block_30_6, KEY_1918301893_3786249548_975574495_634376995,
                         16U);
  DUMP_int(30, _4_sum__block_30_6, 4);
  _cipher$_xtea_encipher(28U, 32U, (unsigned int *)_4_sum__block_28_5, KEY_1918301893_3786249548_975574495_634376995,
                         16U);
  DUMP_int(28, _4_sum__block_28_5, 4);
  _cipher$_xtea_encipher(24U, 32U, (unsigned int *)_4_sum__block_24_4, KEY_1918301893_3786249548_975574495_634376995,
                         16U);
  DUMP_int(24, _4_sum__block_24_4, 4);
  _cipher$_xtea_encipher(26U, 32U, (unsigned int *)_4_sum__block_26_3, KEY_1918301893_3786249548_975574495_634376995,
                         16U);
  DUMP_int(26, _4_sum__block_26_3, 4);
  _cipher$_xtea_encipher(31U, 32U, (unsigned int *)_4_sum__block_31_1, KEY_1918301893_3786249548_975574495_634376995,
                         16U);
  DUMP_int(31, _4_sum__block_31_1, 4);
  return (0);
}
}
