/* Generated by CIL v. 1.7.3 */
/* print_CIL_Input is false */

struct _2_init_tigress_1_opaque_NodeStruct ;
union _3_sum_$node ;
struct _IO_FILE ;
struct timeval ;
struct _2_init_tigress_1_opaque_NodeStruct {
   struct _2_init_tigress_1_opaque_NodeStruct *next ;
   int data ;
   struct _2_init_tigress_1_opaque_NodeStruct *prev ;
};
extern int gettimeofday(struct timeval *tv , void *tz ) ;
extern int pthread_cond_broadcast(int *cond ) ;
char **_global_argv  =    (char **)0;
extern int getpagesize() ;
extern int posix_memalign(void **memptr , unsigned int alignment , unsigned int size ) ;
extern int pthread_join(void *thread , void **value_ptr ) ;
extern unsigned int strlen(char const   *s ) ;
extern int open(char const   *filename , int oflag  , ...) ;
extern int pthread_barrier_destroy(int *barrier ) ;
extern int pthread_mutex_init(int *mutex , int *attr ) ;
extern int strncmp(char const   *s1 , char const   *s2 , unsigned int maxlen ) ;
unsigned long _1_entropy  =    1205847982700084983UL;
extern int ( /* missing proto */  printf)() ;
int _global_argc  =    0;
extern int pthread_cond_signal(int *cond ) ;
struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_ptr_2  =    (struct _2_init_tigress_1_opaque_NodeStruct *)0;
extern int pthread_barrier_init(int *barrier , int *attr , unsigned int count ) ;
extern int raise(int sig ) ;
extern int scanf(char const   *format  , ...) ;
char **_global_envp  =    (char **)0;
extern int unlink(char const   *filename ) ;
extern double difftime(long tv1 , long tv0 ) ;
extern int pthread_barrier_wait(int *barrier ) ;
extern int pthread_mutex_lock(int *mutex ) ;
extern void *memcpy(void *s1 , void const   *s2 , unsigned int size ) ;
unsigned long _1_alwaysZero  =    0;
extern void *dlsym(void *handle , char *symbol ) ;
extern int gethostname(char *name , unsigned int namelen ) ;
extern unsigned long strtoul(char const   *str , char const   *endptr , int base ) ;
extern void abort() ;
extern int fprintf(struct _IO_FILE *stream , char const   *format  , ...) ;
extern void free(void *ptr ) ;
extern void exit(int status ) ;
extern void signal(int sig , void *func ) ;
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) ;
void init_tigress(void) ;
typedef struct _IO_FILE FILE;
extern int mprotect(void *addr , unsigned int len , int prot ) ;
extern int close(int filedes ) ;
extern double log(double x ) ;
extern double strtod(char const   *str , char const   *endptr ) ;
extern double ceil(double x ) ;
struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_ptr_1  =    (struct _2_init_tigress_1_opaque_NodeStruct *)0;
extern int fclose(void *stream ) ;
extern int fcntl(int filedes , int cmd  , ...) ;
extern int pthread_cond_wait(int *cond , int *mutex ) ;
extern void perror(char const   *str ) ;
char const   *_3_sum_$strings  =    "";
extern int pthread_cond_init(int *cond , int *attr ) ;
extern int write(int filedes , void *buf , unsigned int nbyte ) ;
typedef struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_StructureType;
extern int ptrace(int request , void *pid , void *addr , int data ) ;
struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_list_1  =    (struct _2_init_tigress_1_opaque_NodeStruct *)0;
extern unsigned int strnlen(char const   *s , unsigned int maxlen ) ;
extern float strtof(char const   *str , char const   *endptr ) ;
struct timeval {
   long tv_sec ;
   long tv_usec ;
};
extern long clock(void) ;
extern void qsort(void *base , unsigned int nel , unsigned int width , int (*compar)(void *a ,
                                                                                     void *b ) ) ;
extern long time(long *tloc ) ;
extern int read(int filedes , void *buf , unsigned int nbyte ) ;
extern int rand() ;
union _3_sum_$node {
   char _char ;
   unsigned int _unsigned_int ;
   unsigned char _unsigned_char ;
   long _long ;
   unsigned long _unsigned_long ;
   void *_void_star ;
   unsigned short _unsigned_short ;
   unsigned long long _unsigned_long_long ;
   signed char _signed_char ;
   long long _long_long ;
   int _int ;
   short _short ;
};
extern int strcmp(char const   *a , char const   *b ) ;
extern void *fopen(char const   *filename , char const   *mode ) ;
extern double sqrt(double x ) ;
extern int snprintf(char *str , unsigned int size , char const   *format  , ...) ;
extern long strtol(char const   *str , char const   *endptr , int base ) ;
extern void *malloc(unsigned int size ) ;
extern int nanosleep(int *rqtp , int *rmtp ) ;
extern int pthread_mutex_unlock(int *mutex ) ;
extern int atoi(char const   *s ) ;
extern int pthread_create(void *thread , void *attr , void *start_routine , void *arg ) ;
unsigned int _2_init_tigress__opaque_array[30]  = 
  {      258,      691,      3,      308, 
        425,      5,      278,      537, 
        5,      3,      187,      7, 
        33,      12,      57,      358, 
        670,      43,      448,      159, 
        85,      468,      292,      13, 
        143,      243,      80,      498, 
        369};
extern int fseek(struct _IO_FILE *stream , long offs , int whence ) ;
extern int fscanf(struct _IO_FILE *stream , char const   *format  , ...) ;
struct _2_init_tigress_1_opaque_NodeStruct *_2_init_tigress_1_opaque_list_2  =    (struct _2_init_tigress_1_opaque_NodeStruct *)0;
int sum(int x , int y ) ;
void megaInit(void) ;
void megaInit(void) 
{ 


  {

}
}
int sum(int x , int y ) 
{ 
  char _3_sum_$locals[12] ;
  union _3_sum_$node _3_sum_$stack[1][32] ;
  union _3_sum_$node *_3_sum_$sp[1] ;
  void **_3_sum_$pc[1] ;
  void *_3_sum_$array[1][16]  = {{&& _3_sum__local$result_STA_0$value_LIT_0, (void *)8UL,
                                  && _3_sum__formal$result_STA_0$value_LIT_0, (void *)0UL,
                                  && _3_sum__load_int$left_STA_0$result_STA_0, && _3_sum__formal$result_STA_0$value_LIT_0,
                                  (void *)1UL, && _3_sum__load_int$left_STA_0$result_STA_0,
                                  && _3_sum__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1,
                                  && _3_sum__store_int$right_STA_0$left_STA_1, && _3_sum__goto$label_LAB_0,
                                  (void *)1UL, && _3_sum__local$result_STA_0$value_LIT_0,
                                  (void *)8UL, && _3_sum__load_int$left_STA_0$result_STA_0,
                                  && _3_sum__return_int$expr_STA_0}};

  {
  _3_sum_$sp[0] = _3_sum_$stack[0];
  _3_sum_$pc[0] = _3_sum_$array[0];
  goto *(*(_3_sum_$pc[0]));
  Lab_2000001: /* CIL Label */ ;
  _3_sum__load_int$left_STA_0$result_STA_0: /* CIL Label */ ;
  (_3_sum_$pc[0]) ++;
  (_3_sum_$sp[0] + 0)->_int = *((int *)(_3_sum_$sp[0] + 0)->_void_star);
  goto *(*(_3_sum_$pc[0]));
  _3_sum__formal$result_STA_0$value_LIT_0: /* CIL Label */ ;
  (_3_sum_$pc[0]) ++;
  switch (*((int *)_3_sum_$pc[0])) {
  case 1: 
  (_3_sum_$sp[0] + 1)->_void_star = (void *)(& y);
  break;
  case 0: 
  (_3_sum_$sp[0] + 1)->_void_star = (void *)(& x);
  break;
  }
  (_3_sum_$sp[0]) ++;
  (_3_sum_$pc[0]) ++;
  goto *(*(_3_sum_$pc[0]));
  _3_sum__PlusA_int_int2int$right_STA_0$result_STA_0$left_STA_1: /* CIL Label */ ;
  (_3_sum_$pc[0]) ++;
  (_3_sum_$sp[0] + -1)->_int = (_3_sum_$sp[0] + -1)->_int + (_3_sum_$sp[0] + 0)->_int;
  (_3_sum_$sp[0]) --;
  goto *(*(_3_sum_$pc[0]));
  _3_sum__store_int$right_STA_0$left_STA_1: /* CIL Label */ ;
  (_3_sum_$pc[0]) ++;
  *((int *)(_3_sum_$sp[0] + -1)->_void_star) = (_3_sum_$sp[0] + 0)->_int;
  _3_sum_$sp[0] += -2;
  goto *(*(_3_sum_$pc[0]));
  _3_sum__return_int$expr_STA_0: /* CIL Label */ ;
  (_3_sum_$pc[0]) ++;
  return ((_3_sum_$sp[0] + 0)->_int);
  goto *(*(_3_sum_$pc[0]));
  _3_sum__local$result_STA_0$value_LIT_0: /* CIL Label */ ;
  (_3_sum_$pc[0]) ++;
  (_3_sum_$sp[0] + 1)->_void_star = (void *)(_3_sum_$locals + *((int *)_3_sum_$pc[0]));
  (_3_sum_$sp[0]) ++;
  (_3_sum_$pc[0]) ++;
  goto *(*(_3_sum_$pc[0]));
  _3_sum__goto$label_LAB_0: /* CIL Label */ ;
  (_3_sum_$pc[0]) ++;
  _3_sum_$pc[0] += *((int *)_3_sum_$pc[0]);
  goto *(*(_3_sum_$pc[0]));
}
}
void init_tigress(void) 
{ 
  struct _2_init_tigress_1_opaque_NodeStruct *p1 ;
  int i2 ;
  struct _2_init_tigress_1_opaque_NodeStruct *p3 ;
  int _2_init_tigress__BEGIN_1 ;
  int _2_init_tigress__END_1 ;
  int _2_init_tigress__BARRIER_2 ;

  {
  _2_init_tigress__BEGIN_1 = 1;
  p1 = (struct _2_init_tigress_1_opaque_NodeStruct *)malloc(sizeof(struct _2_init_tigress_1_opaque_NodeStruct ));
  p1->next = p1;
  p1->prev = p1;
  _2_init_tigress_1_opaque_list_1 = p1;
  i2 = 0;
  while (i2 < 4) {
    p3 = (struct _2_init_tigress_1_opaque_NodeStruct *)malloc(sizeof(struct _2_init_tigress_1_opaque_NodeStruct ));
    p3->data = i2 * (((_1_entropy + 9) + 1UL) + ((- _1_entropy - 1UL) | (- 9 - 1UL)));
    p3->next = _2_init_tigress_1_opaque_list_1->next;
    p3->prev = _2_init_tigress_1_opaque_list_1;
    (_2_init_tigress_1_opaque_list_1->next)->prev = p3;
    _2_init_tigress_1_opaque_list_1->next = p3;
    i2 ++;
  }
  _2_init_tigress_1_opaque_ptr_1 = _2_init_tigress_1_opaque_list_1->next;
  _2_init_tigress_1_opaque_ptr_2 = _2_init_tigress_1_opaque_ptr_1;
  _2_init_tigress_1_opaque_ptr_2 = _2_init_tigress_1_opaque_ptr_2->next;
  _2_init_tigress__END_1 = 1;
  _2_init_tigress__BARRIER_2 = 1;
  return;
}
}
int main(int _formal_argc , char **_formal_argv , char **_formal_envp ) 
{ 
  int x ;
  int y ;
  int z ;
  int tmp ;
  int _BARRIER_0 ;

  {
  megaInit();
  _global_argc = _formal_argc;
  _global_argv = _formal_argv;
  _global_envp = _formal_envp;
  _BARRIER_0 = 1;
  x = 6;
  y = 9;
  tmp = sum(x, y);
  z = tmp;
  printf("The sum is %d.\n", z);
  return (0);
}
}
